### ISSUE TITLE
Prepare a database diagram

### ISSUE THREAD

**Issue by ronniegnr** [ronniegnr/kothamala#19]

**Comment by shakilsmash** [comment]
kothamala_rough diagram and SQL files are shared on goolge drive with folder name "#kothamala"

**Comment by ronniegnr** [comment]
@shakilsmash 
https://github.com/ronniegnr/kothamala/blob/master/info/kothamala_rough_sql.sql
https://github.com/ronniegnr/kothamala/blob/master/info/kothamala_rough.mwb
